### ISSUE TITLE
how to docker cp recursive?

### ISSUE THREAD

**Issue by vors** [StefanScherer/windows-docker-machine#20] opened 2018-01-20 23:57 UTC
How do I copy files recursively to the docker?

I'm able to copy a single file with

```
docker cp ../powershell_kernel/powershell_kernel/kernel.py epic_gates:\\Python27\\Lib\\site-packages\\powershell_kernel\\kernel.py
```

But 
```
docker cp ../powershell_kernel/powershell_kernel epic_gates:\\Python27\\Lib\\site-packages\\powershell_kernel
```

Doesn't have effect and no error messages.

Googling suggests that it was a problem on old docker versions, but I'm using a new one from edge channel, so should not be old.

**Comment by StefanScherer** [comment] 2018-01-23 13:44
Hm, don't know. It works for me.

**Comment by StefanScherer** [comment] 2018-01-31 15:24
@vors Do you still have the problem?

**Comment by vors** [comment] 2018-01-31 18:59
I workaround it with a for-loop on top of copy, since it work on the individual files.
I didn't try it after that.

One thing I didn't mention is that I'm copying folder over existing folder in the container.

**Comment by StefanScherer** [comment] 2018-01-31 19:09
Ah ok. Yes it's sometimes difficult to write down every step so others can reproduce it in their environment.
So I'm closing this now. If you have further questions let me know. For general questions problems the docker/for-win or moby/moby repo on GitHub are also places to file issues.

**Closed as completed by StefanScherer** 2018-01-31 19:09 UTC
