### ISSUE TITLE
Windows Server 2016 (virtualbox):  Start-Service docker fails on privisioning

### ISSUE THREAD

**Issue by hugo4711** [StefanScherer/windows-docker-machine#35] opened 2018-06-05 09:36 UTC
Docker Engine failed to start as a service during provisioning:
```
Bringing machine '2016' up with 'virtualbox' provider...
==> 2016: Clearing any previously set forwarded ports...
==> 2016: Clearing any previously set network interfaces...
==> 2016: Preparing network interfaces based on configuration...
    2016: Adapter 1: nat
    2016: Adapter 2: hostonly
==> 2016: Forwarding ports...
    2016: 3389 (guest) => 3389 (host) (adapter 1)
    2016: 5985 (guest) => 55985 (host) (adapter 1)
    2016: 5986 (guest) => 55986 (host) (adapter 1)
    2016: 22 (guest) => 2222 (host) (adapter 1)
==> 2016: Running 'pre-boot' VM customizations...
==> 2016: Booting VM...
==> 2016: Waiting for machine to boot. This may take a few minutes...
    2016: WinRM address: 127.0.0.1:55985
    2016: WinRM username: vagrant
    2016: WinRM execution_time_limit: PT2H
    2016: WinRM transport: negotiate
==> 2016: Machine booted and ready!
==> 2016: Checking for guest additions in VM...
==> 2016: Configuring and enabling network interfaces...
==> 2016: Mounting shared folders...
    2016: /Users/nolte => /Users/nolte
==> 2016: Running provisioner: shell...
    2016: Running: scripts/create-machine.ps1 as c:\tmp\vagrant-shell.ps1
    2016: === Generating CA
    2016: === Generating CA public key
    2016: === Generating Server certificate
    2016: === Generating Server private key
    2016: === Generating Client certificate
    2016: === Generating Client key
    2016: === Creating / Updating C:\ProgramData\docker\config\daemon.json
    2016: === Creating / Updating C:\Users\vagrant\.docker\machine\machines\2016\config.json
    2016: === Copying Client certificates to C:\Users\vagrant\.docker\machine\machines\2016
    2016: === Copying Docker Machine configuration to C:/Users/nolte\.docker\machine\machines\2016
    2016: Restarting Docker
    2016: Reducing minimum API version from 1.24 to 1.15
    2016: Replacing '1.24' with '1.15' in file 'C:\Program Files\docker\dockerd.exe'
    2016: Fix already applied.
    2016: Opening Docker TLS port
    2016: Start-Service : Failed to start service 'Docker Engine (docker)'.
    2016: At C:\tmp\vagrant-shell.ps1:308 char:1
    2016: + Start-Service docker
    2016: + ~~~~~~~~~~~~~~~~~~~~
    2016:     + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],  
    2016:    ServiceCommandException
    2016:     + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
    2016: Ok.
```

**Comment by hugo4711** [comment] 2018-06-08 06:56
I have found your [windows_2016_docker Vagrant Box](https://app.vagrantup.com/StefanScherer/boxes/windows_2016_docker) - I used this as a base box and installed docker and docker machine via chocolatey.

Docker 17.10.0 has been installed and the service is up and running. I believe 17.6.x was installed in my test environment. I think this issue can be closed.

**Comment by hugo4711** [comment] 2018-06-08 06:58
I would suggest to simplify the installation scripts of the docker environment by using chocolatey. There is a script `packer-windows/nested/scripts/install-tools.ps1` which can be used.

**Comment by StefanScherer** [comment] 2018-06-08 13:56
The underlying Vagrant Box already should have Docker Engine installed. That's what the windows_2016_docker box is for.
The provision script here does not work with Chocolatey and also should be independent from Chocolatey.
The choco package "docker" only installs the Docker CLI which wouldn't be enough to run Windows containers.
And the docker-machine binary is not needed in this setup. But thanks for the suggestions.

**Comment by frankrobert** [comment] 2018-06-08 16:36
@StefanScherer I'm also experiencing the same issue as @hugo4711 where the `Start-Service docker` command fails to execute when attempting to bring up the box from Vagrant Cloud.

Here's what happens after I try to bring up the box and use the docker-machine commands as instructed:

![machine](https://user-images.githubusercontent.com/4380529/41169896-5ff97910-6b18-11e8-8527-359a9d8bf31b.png)

It seems that I cannot connect to the docker-machine due to this error. Any thoughts on how to correct this?

Here's some system info if it helps at all:
![image](https://user-images.githubusercontent.com/4380529/41169940-7c9a8186-6b18-11e8-8f9d-b9f2816b2ed0.png)
![image](https://user-images.githubusercontent.com/4380529/41169948-8404348a-6b18-11e8-9f4b-8af756755f4c.png)

**Comment by StefanScherer** [comment] 2018-06-08 17:06
Thanks @frankrobert for reporting.
Can @hugo4711 and you report which version of VirtualBox you are running the box?

I'll try my Vagrant box v2018.04.10 with current VirtualBox in the meantime and see if I can reproduce the error.
I normally use the VMware Fusion variant so maybe the VirtualBox Vagrant box has some issues I'm not aware off.

**Comment by frankrobert** [comment] 2018-06-08 17:59
@StefanScherer I had installed the VirtualBox GUI for Mac.
```
VirtualBox Graphical User Interface
Version 5.2.6 r120293 (Qt5.6.3)
```

I believe there is a minor update available.

**Comment by StefanScherer** [comment] 2018-06-08 20:25
I can reproduce the problem. It was introduced with #34.
As a workaround you can checkout an older commit

```
git checkout cd08ed
```

And then run `vagrant provision 2016-box` again.

I'll fix that, but probably add a CI step to test the create-machine.ps1 first.

**Comment by StefanScherer** [comment] 2018-06-08 21:14
OK, AppVeyor build tests the create-machine.ps1. The problem is fixed with #36.
Thanks for reporting this.

**Closed as completed by StefanScherer** 2018-06-08 21:14 UTC
Labels: host/windows, host/macos, hypervisor/virtualbox

**Comment by hugo4711** [comment] 2018-06-09 08:31
Just for the sake of completeness:
```
 VirtualBox 5.2.8 r121009 (Qt5.6.3)
```

**Comment by StefanScherer** [comment] 2018-06-09 09:38
Thanks @hugo4711 VirtualBox 5.2 is good. Try the lastest create-machine.ps1 which should solve your problem.

**Comment by hugo4711** [comment] 2018-06-09 12:49
Just tried it. It works! Thanks a lot!
